### ISSUE TITLE
Not displaying correct cluster title

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-activejobs#122]
It seems you are displaying the cluster id instead of the cluster title in the "Cluster" column. For example at PSC they have a cluster config file that looks like:

```yaml
# /etc/ood/config/clusters.d/cluster1.yml
v2:
 metadata:
   title: "Bridges"
 login:
   host: "bridges.psc.edu"
 job: 
   adapter: "slurm" 
#   cluster: "Bridges" 
   bin:  "/opt/packages/slurm/15.08.8/bin"
```

but in the Active Jobs app it doesn't show "Bridges" in the "Cluster" column but instead shows the titleized form of the cluster id:

![image](https://cloud.githubusercontent.com/assets/4260509/26802226/bd4c3184-4a0d-11e7-802a-76004a120e3a.png)
